#!/usr/bin/env bash

cd "$(dirname "$0")/.."

EDITION_PATH='editions/github'

tiddler_text() {
  awk '!body && /^$/ { body = 1; next; } body { print; }'
}

buildinfo_tid_body() {
  local dir="$1"
  local vprefix="$2"
  local ver="$3"
  local changes=$(git diff --pretty=oneline "$vprefix$ver..HEAD" -- "$dir" 2>&1)

  if [[ -n $changes ]]; then
    echo "Changes between version $ver and HEAD:"
    echo ''
    echo '```'
    echo "$changes" |
      grep -E -v '^[+-](created|modified):' |
      grep -E -v '^(diff|index) '
    echo '```'
  else
    echo "No changes between version $ver and HEAD."
  fi
}

buildinfo_tid() {
  local dir="$1"
  local vprefix="$2"
  local ver="$3"
  local now="$(TZ=UTC date +'%Y%m%d%H%M%S')"

  cat <<EOS
title: $vprefix$ver-current
caption: >$ver
tags: $:/tags/ReleaseNotes
created: $now
modified: $now
released: $now

$(buildinfo_tid_body "$dir" "$vprefix" "$ver")
EOS
}

make_buildinfo() {
  local dir="$1"
  local vprefix="$2"
  local name=$(dirname $vprefix)
  local out="$EDITION_PATH/tiddlers/content/${name}_current.tid"
  local ver=$(jq -r .version "$dir"/plugin.info)
  local new="$(buildinfo_tid "$dir" "$vprefix" "$ver")"

  if [[ -f $out ]]; then
    if [[ "$(tiddler_text <<<"$new")" = "$(tiddler_text <"$out")" ]]; then
      echo "$out is already up-to-date."
      return
    else
      echo "Writing $out."
      tiddler_text <<<"$new" >/tmp/a
      tiddler_text <"$out" >/tmp/b
      diff -u /tmp/a /tmp/b
      echo $?
    fi
  fi

  printf '%s' "$new" >"$out"
}

for pluginPath in plugins/*/* themes/*/*; do
  plugin=$(basename "$pluginPath")
  prefix="$plugin/v"

  if [[ -d $pluginPath ]]; then
    make_buildinfo "$pluginPath" "$prefix"
  fi
done

cp package.json $EDITION_PATH/tiddlers/files/package

# npm 3.10.10 stopped updating package-lock.json
if [ -f package-lock.json ]; then
  cp package-lock.json $EDITION_PATH/tiddlers/files/package-lock
else
  cp package.json $EDITION_PATH/tiddlers/files/package-lock
fi
